x-service-templates:
#   payment-processor: &payment-processor
#     image: "minha-img-rinha" #zanfranceschi/payment-processor:amd64
#     networks:
#       - payment-processor
#     deploy:
#       resources:
#         limits:
#           cpus: "1.5"
#           memory: "100MB"
  
  payment-processor-db: &payment-processor-db
    image: postgres:17-alpine
    networks:
      - payment-processor
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c max_connections=450 -c shared_buffers=32MB -c effective_cache_size=96MB -c work_mem=3MB -c maintenance_work_mem=12MB -c synchronous_commit=off -c fsync=off
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rinha -d rinha"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "250MB"

services:

  payment-processor-db-1:
    <<: *payment-processor-db
    container_name: payment-processor-db
    hostname: payment-processor-db
    ports:
      - 5432:5432

  # payment-processor-1:
  #   <<: *payment-processor
  #   container_name: payment-processor-default
  #   hostname: payment-processor-default
  #   environment:
  #     - TRANSACTION_FEE=0.05
  #     - RATE_LIMIT_SECONDS=5
  #     - INITIAL_TOKEN=123
  #     - DB_CONNECTION_STRING=Host=payment-processor-db;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
  #   ports:
  #     - 8001:8080
  #   depends_on:
  #     - payment-processor-db-1
    
  # payment-processor-2:
  #   <<: *payment-processor
  #   container_name: payment-processor-fallback
  #   hostname: payment-processor-fallback
  #   environment:
  #     - TRANSACTION_FEE=0.15
  #     - RATE_LIMIT_SECONDS=5
  #     - INITIAL_TOKEN=123
  #     - DB_CONNECTION_STRING=Host=payment-processor-db;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
  #   ports:
  #     - 8002:8080
  #   depends_on:
  #     - payment-processor-db-1

networks:
  payment-processor:
    name: payment-processor
    driver: bridge